// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyaH6dPSJ0WTxlbJDZzKjnfPfjkvhc5nQ',
    appId: '1:283680594868:web:20acfbe7f47f9a250970e1',
    messagingSenderId: '283680594868',
    projectId: 'kafe-5506f',
    authDomain: 'kafe-5506f.firebaseapp.com',
    storageBucket: 'kafe-5506f.appspot.com',
    measurementId: 'G-X2J7WK4502',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII_Rr__Pqj0XOi2qS2-u-M8CC9NM0rSc',
    appId: '1:283680594868:android:e64f1579e064e7f70970e1',
    messagingSenderId: '283680594868',
    projectId: 'kafe-5506f',
    storageBucket: 'kafe-5506f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7Z3ujBVWiniesm-qoFFY_p36V8lVF6o',
    appId: '1:283680594868:ios:fb138b7a89a2c2af0970e1',
    messagingSenderId: '283680594868',
    projectId: 'kafe-5506f',
    storageBucket: 'kafe-5506f.appspot.com',
    iosBundleId: 'com.example.kafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7Z3ujBVWiniesm-qoFFY_p36V8lVF6o',
    appId: '1:283680594868:ios:fb138b7a89a2c2af0970e1',
    messagingSenderId: '283680594868',
    projectId: 'kafe-5506f',
    storageBucket: 'kafe-5506f.appspot.com',
    iosBundleId: 'com.example.kafeApp',
  );
}
